import js from '@eslint/js';
import tseslint from 'typescript-eslint';

export default tseslint.config(
  {
    ignores: [
      '**/dist/**',
      '**/.next/**',
      '**/node_modules/**',
      '**/coverage/**',
      '**/.turbo/**',
      // Generated by `next build`/`next dev` with a triple-slash reference;
      // Next overwrites any manual edit, so lint must ignore it.
      '**/next-env.d.ts',
    ],
  },
  js.configs.recommended,
  ...tseslint.configs.recommendedTypeChecked,
  {
    languageOptions: {
      parserOptions: {
        projectService: true,
        tsconfigRootDir: import.meta.dirname,
      },
    },
    rules: {
      // CLAUDE.md: no `any` without a justifying comment. An eslint-disable
      // with `-- reason` is the sanctioned escape hatch.
      '@typescript-eslint/no-explicit-any': 'error',
      // Sensitive data must never reach stdout; use the structured logger.
      'no-console': 'error',
      '@typescript-eslint/explicit-module-boundary-types': 'error',
      '@typescript-eslint/no-floating-promises': 'error',
      '@typescript-eslint/no-misused-promises': 'error',
      '@typescript-eslint/no-unused-vars': [
        'error',
        { argsIgnorePattern: '^_', varsIgnorePattern: '^_', ignoreRestSiblings: true },
      ],
    },
  },
  {
    files: ['**/*.js', '**/*.mjs', '**/*.cjs'],
    ...tseslint.configs.disableTypeChecked,
  },
  {
    // CommonJS tooling files (jest configs, presets).
    files: ['**/jest.config.js', 'packages/config/jest.js'],
    languageOptions: {
      sourceType: 'commonjs',
      globals: { require: 'readonly', module: 'writable', __dirname: 'readonly' },
    },
    rules: {
      '@typescript-eslint/no-require-imports': 'off',
    },
  },
  {
    // CI helper scripts run on the runner, not in a service: they are Node
    // programs whose entire job is to print a verdict to the build log, so the
    // no-console rule (which exists to keep sensitive data out of service
    // stdout) does not apply. They never touch user data.
    files: ['.github/scripts/**/*.mjs'],
    languageOptions: {
      globals: { process: 'readonly', console: 'readonly' },
    },
    rules: {
      'no-console': 'off',
    },
  },
  {
    // Zone A audit surface: @estate/vault-crypto runs on the user's device and
    // holds the only keys that can open the vault, so its dependency tree must
    // stay empty (docs/04 boundary rule 3, threat model TB6 / risk #4). Only
    // relative imports are allowed inside src/ — no packages, and not even
    // node: builtins, which would also break the browser build.
    //
    // no-restricted-imports is the wrong tool here: its `patterns` groups use
    // gitignore-style matching, where `*` never crosses a `/`, so deep
    // specifiers like '@noble/hashes/sha256' slip through. Matching on the AST
    // source value is exact.
    files: ['packages/vault-crypto/src/**/*.ts'],
    rules: {
      'no-restricted-syntax': [
        'error',
        {
          selector: 'ImportDeclaration[source.value=/^[^.]/]',
          message: '@estate/vault-crypto must have zero dependencies: relative imports only.',
        },
        {
          selector: 'ImportExpression[source.value=/^[^.]/]',
          message: '@estate/vault-crypto must have zero dependencies: relative imports only.',
        },
        {
          selector: 'ExportNamedDeclaration[source.value=/^[^.]/]',
          message: '@estate/vault-crypto must have zero dependencies: relative re-exports only.',
        },
        {
          selector: 'ExportAllDeclaration[source.value=/^[^.]/]',
          message: '@estate/vault-crypto must have zero dependencies: relative re-exports only.',
        },
        {
          selector: 'TSImportType[argument.value=/^[^.]/]',
          message: '@estate/vault-crypto must have zero dependencies: relative type imports only.',
        },
        {
          selector: "CallExpression[callee.name='require']",
          message: '@estate/vault-crypto must have zero dependencies: relative imports only.',
        },
      ],
    },
  },
  {
    // Zone boundary: frontend code must never import server-side key handling
    // or database internals. (threat model TB6 / architecture zone rules)
    files: ['apps/web/**'],
    rules: {
      'no-restricted-imports': [
        'error',
        {
          paths: [
            {
              name: '@estate/crypto',
              message:
                'Server-side crypto never ships to the client. Use @estate/vault-crypto for Zone A.',
            },
            {
              name: '@estate/db',
              message: 'Database access happens in services, never in the frontend.',
            },
          ],
        },
      ],
    },
  },
);
