import js from '@eslint/js';
import tseslint from 'typescript-eslint';

export default tseslint.config(
  {
    ignores: [
      '**/dist/**',
      '**/.next/**',
      '**/node_modules/**',
      '**/coverage/**',
      '**/.turbo/**',
      /*
       * GIT WORKTREES CHECKED OUT INSIDE THE REPO.
       *
       * A worktree under `.claude/worktrees/<name>` is a SECOND FULL CHECKOUT of
       * this repository, so `eslint .` from the root descends into it and lints
       * every file twice — once at its real path and once at a path that is not
       * repo source at all. In practice that means tens of thousands of errors
       * from files outside every tsconfig project, plus somebody else's
       * in-progress work reported as if it were yours, which makes `pnpm lint`
       * unusable locally the moment two people work in parallel. CI is a clean
       * checkout and never sees one.
       *
       * Ignoring the path is right rather than convenient: the worktree's files
       * ARE linted, at their own root, by the session working in them.
       */
      '.claude/worktrees/**',
      // Generated by `next build`/`next dev` with a triple-slash reference;
      // Next overwrites any manual edit, so lint must ignore it.
      '**/next-env.d.ts',
      // The vault origin's BROWSER BUNDLE, emitted by tsconfig.client.json.
      // It lands under `public/` rather than `dist/` because that is the tree
      // the edge serves; it is still build output, and linting it reports the
      // compiler's own JS back as untyped source.
      'apps/vault-web/public/app/**',
      // The operator origin's browser bundle (M21 PR3a), same status. It has no
      // `public/lib/**` counterpart: this origin imports no vault-crypto, which
      // is the point of it being a separate deployable rather than a route on
      // the vault edge.
      'apps/operator-web/public/app/**',
      // vault-crypto's browser build, copied in by the same package's build
      // step. Emitted JavaScript, linted at its source in packages/.
      'apps/vault-web/public/lib/**',
      // Plain Node ESM build scripts, outside every tsconfig project — the
      // same status .github/scripts has.
      'apps/vault-web/scripts/**',
      'apps/vault-extension/scripts/**',
      // The vault-crypto BROWSER emit. Same sources as dist/, different module
      // format; linting the output reports the compiler's JS back as untyped.
      '**/dist-esm/**',
    ],
  },
  js.configs.recommended,
  ...tseslint.configs.recommendedTypeChecked,
  {
    languageOptions: {
      parserOptions: {
        projectService: true,
        tsconfigRootDir: import.meta.dirname,
      },
    },
    rules: {
      // CLAUDE.md: no `any` without a justifying comment. An eslint-disable
      // with `-- reason` is the sanctioned escape hatch.
      '@typescript-eslint/no-explicit-any': 'error',
      // Sensitive data must never reach stdout; use the structured logger.
      'no-console': 'error',
      '@typescript-eslint/explicit-module-boundary-types': 'error',
      '@typescript-eslint/no-floating-promises': 'error',
      '@typescript-eslint/no-misused-promises': 'error',
      '@typescript-eslint/no-unused-vars': [
        'error',
        { argsIgnorePattern: '^_', varsIgnorePattern: '^_', ignoreRestSiblings: true },
      ],
    },
  },
  {
    files: ['**/*.js', '**/*.mjs', '**/*.cjs'],
    ...tseslint.configs.disableTypeChecked,
  },
  {
    // CommonJS tooling files (jest configs, presets).
    files: ['**/jest.config.js', 'packages/config/jest.js'],
    languageOptions: {
      sourceType: 'commonjs',
      globals: { require: 'readonly', module: 'writable', __dirname: 'readonly' },
    },
    rules: {
      '@typescript-eslint/no-require-imports': 'off',
    },
  },
  {
    // `packages/config/ci-guard.js` is CommonJS tooling like the presets above,
    // but it also REGISTERS jest cases — the shared CI guard every package's
    // `ci-guard.spec.ts` calls — so it needs the test globals as well. It is
    // named explicitly rather than folded into a `packages/config/*.js` glob,
    // because handing jest globals to every future file in that directory is
    // how a preset quietly starts being allowed to declare tests.
    files: ['packages/config/ci-guard.js'],
    languageOptions: {
      sourceType: 'commonjs',
      globals: {
        module: 'writable',
        process: 'readonly',
        describe: 'readonly',
        it: 'readonly',
        expect: 'readonly',
      },
    },
  },
  {
    // CI helper scripts run on the runner, not in a service: they are Node
    // programs whose entire job is to print a verdict to the build log, so the
    // no-console rule (which exists to keep sensitive data out of service
    // stdout) does not apply. They never touch user data.
    files: ['.github/scripts/**/*.mjs'],
    languageOptions: {
      // `fetch` is a Node 18+ global. It was absent here only because
      // gate-image-scan.mjs reads a file and makes no request; notify-failure.mjs
      // is the first of these to call an API.
      globals: { process: 'readonly', console: 'readonly', fetch: 'readonly' },
    },
    rules: {
      'no-console': 'off',
      // These are plain .mjs, so a rule demanding TypeScript annotations on
      // exported functions cannot be satisfied — and the exports are what make
      // the logic unit-testable without a live GitHub repository, which matters
      // more here than in a script with no exports at all.
      '@typescript-eslint/explicit-module-boundary-types': 'off',
    },
  },
  {
    // Zone A audit surface: @estate/vault-crypto runs on the user's device and
    // holds the only keys that can open the vault, so its dependency tree must
    // stay empty (docs/04 boundary rule 3, threat model TB6 / risk #4). Only
    // relative imports are allowed inside src/ — no packages, and not even
    // node: builtins, which would also break the browser build.
    //
    // no-restricted-imports is the wrong tool here: its `patterns` groups use
    // gitignore-style matching, where `*` never crosses a `/`, so deep
    // specifiers like '@noble/hashes/sha256' slip through. Matching on the AST
    // source value is exact.
    files: ['packages/vault-crypto/src/**/*.ts'],
    rules: {
      'no-restricted-syntax': [
        'error',
        {
          selector: 'ImportDeclaration[source.value=/^[^.]/]',
          message: '@estate/vault-crypto must have zero dependencies: relative imports only.',
        },
        {
          selector: 'ImportExpression[source.value=/^[^.]/]',
          message: '@estate/vault-crypto must have zero dependencies: relative imports only.',
        },
        {
          selector: 'ExportNamedDeclaration[source.value=/^[^.]/]',
          message: '@estate/vault-crypto must have zero dependencies: relative re-exports only.',
        },
        {
          selector: 'ExportAllDeclaration[source.value=/^[^.]/]',
          message: '@estate/vault-crypto must have zero dependencies: relative re-exports only.',
        },
        {
          selector: 'TSImportType[argument.value=/^[^.]/]',
          message: '@estate/vault-crypto must have zero dependencies: relative type imports only.',
        },
        {
          selector: "CallExpression[callee.name='require']",
          message: '@estate/vault-crypto must have zero dependencies: relative imports only.',
        },
      ],
    },
  },
  {
    // Zone boundary: frontend code must never import server-side key handling
    // or database internals. (threat model TB6 / architecture zone rules)
    files: ['apps/web/**'],
    rules: {
      'no-restricted-imports': [
        'error',
        {
          paths: [
            {
              name: '@estate/crypto',
              message:
                'Server-side crypto never ships to the client. Use @estate/vault-crypto for Zone A.',
            },
            {
              name: '@estate/db',
              message: 'Database access happens in services, never in the frontend.',
            },
          ],
        },
      ],
    },
  },
);
